name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore -f net6.0
    - name: Build
      run: dotnet build --no-restore -f net6.0
    - name: Test
      run: dotnet test --no-build --verbosity normal
