name: CI/CD

on:
  push:
    paths-ignore:
    - 'src/FastCache.Sanbox/**'
    - 'src/FastCache.Benchmarks/**'
    - 'examples/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          3.1.x
          6.0.x
          7.0.x
        include-prerelease: true

    - name: Build, Test, Pack, Publish
      shell: bash
      run: |
        dotnet tool install -g dotnet-releaser
        dotnet-releaser run --nuget-token "${{secrets.NUGET_TOKEN}}" --github-token "${{secrets.GITHUB_TOKEN}}" dotnet-releaser.toml
