name: CI/CD

on:
  push:
    paths-ignore:
    - 'src/FastCache.Sanbox/**'
    - 'examples/**'
  pull_request:

jobs:
  all-in-one:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          6.0.x
          8.0.x
          9.0.x
    - name: Build, Test, Pack, Publish
      shell: bash
      env:
        FASTCACHE_CONSIDER_GC: true
        FASTCACHE_GC_THRESHOLD: 1024
        FASTCACHE_PARALLEL_EVICTION_THRESHOLD: 2048
        FASTCACHE_QUICKLIST_EVICTION_INTERVAL: 00:00:01
      run: |
        dotnet tool install -g dotnet-releaser
        dotnet-releaser run --nuget-token "${{secrets.NUGET_TOKEN}}" --github-token "${{secrets.GITHUB_TOKEN}}" dotnet-releaser.toml

  tests-extra-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          6.0.x
          8.0.x
    - name: Build, Test, Pack, Publish
      shell: pwsh
      env:
        FASTCACHE_CONSIDER_GC: true
        FASTCACHE_GC_THRESHOLD: 1024
        FASTCACHE_PARALLEL_EVICTION_THRESHOLD: 2048
        FASTCACHE_QUICKLIST_EVICTION_INTERVAL: 00:00:01
      run: |
        dotnet test -c release
